### PR TITLE
Adding the hyperfluent grub theme

### PR DESCRIPTION
**Pull request by Daru-san**
Hi, I found this really interesting grub theme and I love the idea of this flake. The grub theme is hyperfluent from https://github.com/Coopydood/HyperFluent-GRUB-Theme

### CODE REVIEW

**Comment by jeslie0** [comment]
Looks good to me! I am not in a position to test that it works, but I am happy to merge it in and let you test it. I will give it a test when I can.

**Comment by Daru-san** [comment]
Awesome, but it seems to me like, judging by the result of the test, that the sha256 hash may be wrong, although it worked for me at first

**Comment by jeslie0** [comment]
I have updated the hash so that the check now passes. Let me know if you have any issues! Thank you for contributing to this repo.

**Comment by Daru-san** [comment]
Great. Everything's good so far

**Pull request merged**
